version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanban.exercise.com
    command: yarn run start
    volumes:
      - ./app/node_modules
      - ./app:/app
    ports:
      - "9000:9000"
